export const INITIAL_SHOP_ITEMS = [
  {
    slug: "title-the-focused",
    name: "The Focused",
    description: "A prestigious title bestowed upon those who fix their gaze on the horizon and never falter.",
    category: "TITLE",
    price: 45,
    levelRequirement: 1,
    effectKey: "The Focused",
  },
  {
    slug: "avatar-scholar",
    name: "Archivist Scholar",
    description: "An arcane researcher draped in indigo robes who unravels the deepest mysteries of the codex.",
    category: "AVATAR",
    price: 60,
    levelRequirement: 1,
    effectKey: "avatar-scholar",
  },
  {
    slug: "theme-crimson-covenant",
    name: "Crimson Covenant",
    description: "Bathes the entire Arcane Codex in intense blood-moon hues, crimson embers, and dark gold accents.",
    category: "THEME",
    price: 90,
    levelRequirement: 2,
    effectKey: "theme-crimson",
  },
  {
    slug: "theme-emerald-grove",
    name: "Emerald Grove",
    description: "Infuses your journal with lush verdant tones, ancient druidic runes, and soothing jade luminescence.",
    category: "THEME",
    price: 120,
    levelRequirement: 2,
    effectKey: "theme-emerald",
  },
  {
    slug: "badge-initiate-sigil",
    name: "Initiate Sigil",
    description: "A decorative bronze badge engraved with the ancient seal of the Adventurers Guild.",
    category: "BADGE",
    price: 30,
    levelRequirement: 1,
    effectKey: "badge-initiate-sigil",
  },
  {
    slug: "frame-golden-aegis",
    name: "Golden Aegis Frame",
    description: "An ornate gilded frame forged in dragon-fire to frame your hero portrait.",
    category: "FRAME",
    price: 300,
    levelRequirement: 3,
    effectKey: "frame-golden-aegis",
  },
];

export const INITIAL_ACHIEVEMENTS = [
  {
    slug: "first-quest",
    title: "First Steps into Legend",
    description: "Complete your very first real-world quest.",
    icon: "award",
    category: "QUEST",
    requiredValue: 1,
  },
  {
    slug: "quests-10",
    title: "Journeyman of the Realm",
    description: "Complete 10 real-world quests.",
    icon: "shield",
    category: "QUEST",
    requiredValue: 10,
  },
  {
    slug: "quests-50",
    title: "Veteran of Deeds",
    description: "Complete 50 real-world quests.",
    icon: "swords",
    category: "QUEST",
    requiredValue: 50,
  },
  {
    slug: "streak-7",
    title: "Unbroken Resolve",
    description: "Maintain a consecutive 7-day activity streak.",
    icon: "flame",
    category: "STREAK",
    requiredValue: 7,
  },
  {
    slug: "streak-30",
    title: "Iron Discipline",
    description: "Maintain a consecutive 30-day activity streak.",
    icon: "zap",
    category: "STREAK",
    requiredValue: 30,
  },
  {
    slug: "level-5",
    title: "Ascended Hero",
    description: "Reach character Level 5.",
    icon: "crown",
    category: "LEVEL",
    requiredValue: 5,
  },
  {
    slug: "intellect-1000",
    title: "Arcane Sage",
    description: "Amass 1,000 Intellect Experience Points.",
    icon: "book-open",
    category: "ATTRIBUTE",
    requiredValue: 1000,
  },
  {
    slug: "first-purchase",
    title: "Merchant's Patron",
    description: "Purchase your first cosmetic treasure in the Bazaar.",
    icon: "coins",
    category: "ECONOMY",
    requiredValue: 1,
  },
  {
    slug: "boss-slayer",
    title: "Bane of Delay",
    description: "Vanquish Procrastinus, Keeper of Delay in weekly combat.",
    icon: "skull",
    category: "BOSS",
    requiredValue: 1,
  },
];

export const INITIAL_TEMPLATES = [
  // STRENGTH (11 templates)
  {
    slug: "str-walk-20",
    title: "Brisk 20-Minute Walk",
    description: "Step outdoors or onto the treadmill for a brisk 20-minute movement session to refresh circulation.",
    attribute: "STRENGTH",
    difficulty: "EASY",
    cadence: "DAILY",
    category: "Movement",
  },
  {
    slug: "str-bodyweight-workout",
    title: "Bodyweight Circuit Training",
    description: "Complete 3 rounds of push-ups, bodyweight squats, lunges, and a 45-second plank.",
    attribute: "STRENGTH",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Fitness",
  },
  {
    slug: "str-mobility-routine",
    title: "Full-Body Mobility & Stretching",
    description: "Spend 15 minutes opening tight hips, shoulders, hamstrings, and thoracic spine.",
    attribute: "STRENGTH",
    difficulty: "EASY",
    cadence: "DAILY",
    category: "Recovery",
  },
  {
    slug: "str-gym-session",
    title: "Weightlifting Strength Session",
    description: "Execute a structured compound resistance workout focusing on progressive overload.",
    attribute: "STRENGTH",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Fitness",
  },
  {
    slug: "str-cycling-ride",
    title: "Outdoor or Stationary Cycle Ride",
    description: "Pedal for at least 30 minutes at a moderate aerobic heart-rate zone.",
    attribute: "STRENGTH",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Cardio",
  },
  {
    slug: "str-sport-practice",
    title: "Sport Skill & Conditioning Session",
    description: "Play tennis, basketball, soccer, swimming, or martial arts practice for 45 minutes.",
    attribute: "STRENGTH",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Sport",
  },
  {
    slug: "str-morning-stretch",
    title: "Morning Sun Salutation & Core Wakeup",
    description: "Perform 10 minutes of gentle morning yoga postures before starting the workday.",
    attribute: "STRENGTH",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Recovery",
  },
  {
    slug: "str-stair-climb",
    title: "Take the Stairs Over the Elevator",
    description: "Consciously choose stairs for all vertical travel during the day.",
    attribute: "STRENGTH",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Habit",
  },
  {
    slug: "str-posture-reset",
    title: "Ergonomic Posture Reset & Wall Angels",
    description: "Perform 3 sets of 12 wall angels and neck retractions to counteract screen slouch.",
    attribute: "STRENGTH",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Mobility",
  },
  {
    slug: "str-5k-run",
    title: "5K Run or Jog",
    description: "Run at a steady aerobic pace for 5 kilometers or 30 uninterrupted minutes.",
    attribute: "STRENGTH",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Cardio",
  },
  {
    slug: "str-ruck-walk",
    title: "Loaded Ruck / Nature Hike",
    description: "Hike a trail or walk with a weighted backpack for 45 minutes.",
    attribute: "STRENGTH",
    difficulty: "EPIC",
    cadence: "WEEKLY",
    category: "Endurance",
  },

  // INTELLECT (20 templates - Learning Fields)
  // --- IT / Tech Fields ---
  {
    slug: "int-software-engineering",
    title: "Software Engineering",
    description: "Study concepts, patterns, and practices related to software engineering.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Engineering",
  },
  {
    slug: "int-cloud-computing",
    title: "Cloud Computing",
    description: "Learn about cloud architectures, AWS, GCP, Azure, or DevOps practices.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "DevOps",
  },
  {
    slug: "int-cybersecurity",
    title: "Cybersecurity",
    description: "Study network security, ethical hacking, cryptography, or threat modeling.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Security",
  },
  {
    slug: "int-data-science-ml",
    title: "Data Science & Machine Learning",
    description: "Study statistics, data analysis, neural networks, or AI models.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Data Science",
  },
  {
    slug: "int-ui-ux-design",
    title: "UI/UX Design",
    description: "Study user interfaces, user experience, typography, and wireframing.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Design",
  },
  {
    slug: "int-web-development",
    title: "Web Development",
    description: "Learn about frontend or backend frameworks, HTML, CSS, JavaScript, and web APIs.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Engineering",
  },
  {
    slug: "int-mobile-development",
    title: "Mobile Development",
    description: "Study iOS, Android, Flutter, or React Native app development.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Engineering",
  },
  {
    slug: "int-blockchain-web3",
    title: "Blockchain & Web3",
    description: "Study smart contracts, decentralized apps, and cryptographic ledgers.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Engineering",
  },

  // --- Non-IT / Arts & Humanities ---
  {
    slug: "int-history",
    title: "History",
    description: "Study historical events, ancient civilizations, or modern history.",
    attribute: "INTELLECT",
    difficulty: "EASY",
    cadence: "WEEKLY",
    category: "History",
  },
  {
    slug: "int-philosophy",
    title: "Philosophy",
    description: "Study philosophical concepts, logic, ethics, and epistemology.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Philosophy",
  },
  {
    slug: "int-literature",
    title: "Literature & Creative Writing",
    description: "Study classic literature, narrative structures, or practice creative writing.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Writing",
  },
  {
    slug: "int-linguistics",
    title: "Linguistics & Languages",
    description: "Study the structure of language, etymology, or learn a new foreign language.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Language",
  },

  // --- Business / Finance ---
  {
    slug: "int-personal-finance",
    title: "Personal Finance & Economics",
    description: "Study investing, macro/micro economics, budgeting, and financial markets.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Finance",
  },
  {
    slug: "int-business-management",
    title: "Business Management",
    description: "Study organizational behavior, leadership, operations, and business strategy.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Management",
  },
  {
    slug: "int-marketing",
    title: "Marketing & Sales",
    description: "Study consumer psychology, brand strategy, digital marketing, and SEO.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Marketing",
  },

  // --- Sciences & Medical ---
  {
    slug: "int-physics-astronomy",
    title: "Physics & Astronomy",
    description: "Study the laws of physics, quantum mechanics, astrophysics, or the cosmos.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Science",
  },
  {
    slug: "int-biology-medicine",
    title: "Biology & Medicine",
    description: "Study human anatomy, genetics, cellular biology, or medical sciences.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Medical",
  },
  {
    slug: "int-psychology-sociology",
    title: "Psychology & Sociology",
    description: "Study human behavior, cognitive science, social structures, and mental health.",
    attribute: "INTELLECT",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Psychology",
  },
  {
    slug: "int-chemistry",
    title: "Chemistry",
    description: "Study organic/inorganic chemistry, molecular structures, and reactions.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Science",
  },
  {
    slug: "int-law-jurisprudence",
    title: "Law & Jurisprudence",
    description: "Study legal systems, constitutional law, contracts, and legal theory.",
    attribute: "INTELLECT",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Law",
  },

  // DISCIPLINE (10 templates)
  {
    slug: "dis-plan-tomorrow",
    title: "Evening Debrief & Tomorrow Planning",
    description: "Review today's accomplishments, set tomorrow's top 3 priorities, and prep your calendar.",
    attribute: "DISCIPLINE",
    difficulty: "EASY",
    cadence: "DAILY",
    category: "Planning",
  },
  {
    slug: "dis-clean-workspace",
    title: "Reset Desk & Workspace to Neutral",
    description: "Clear coffee mugs, file loose papers, wipe surfaces, and leave your desk pristine.",
    attribute: "DISCIPLINE",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Environment",
  },
  {
    slug: "dis-eat-the-frog",
    title: "Tackle the Hardest Task Before Noon",
    description: "Confront the one intimidating task you've been putting off as your first priority.",
    attribute: "DISCIPLINE",
    difficulty: "HARD",
    cadence: "DAILY",
    category: "Execution",
  },
  {
    slug: "dis-screen-limit",
    title: "Digital Fast from Distracting Apps",
    description: "Keep social media and doom-scrolling apps closed for a 4-hour working window.",
    attribute: "DISCIPLINE",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Focus",
  },
  {
    slug: "dis-inbox-zero",
    title: "Process Email & Messages to Zero",
    description: "Sort, archive, delegate, or reply to all unread communications without letting them linger.",
    attribute: "DISCIPLINE",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Organization",
  },
  {
    slug: "dis-financial-audit",
    title: "Weekly Expense & Budget Audit",
    description: "Log recent receipts, reconcile accounts, and verify alignment with personal savings goals.",
    attribute: "DISCIPLINE",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Finance",
  },
  {
    slug: "dis-prepare-materials",
    title: "Prepare Tools & Outfit the Night Before",
    description: "Layout clothes, charge equipment, and pack your bag before going to sleep.",
    attribute: "DISCIPLINE",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Preparation",
  },
  {
    slug: "dis-strict-bedtime",
    title: "Honor Scheduled Bedtime Window",
    description: "Turn off screens and climb into bed within your target 30-minute sleep schedule.",
    attribute: "DISCIPLINE",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Sleep",
  },
  {
    slug: "dis-declutter-room",
    title: "Deep Room / Closet Decluttering",
    description: "Spend 45 minutes donating unused goods and organizing storage spaces.",
    attribute: "DISCIPLINE",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Environment",
  },
  {
    slug: "dis-weekly-review",
    title: "Comprehensive Weekly System Review",
    description: "Perform David Allen GTD-style weekly review of all active projects and open loops.",
    attribute: "DISCIPLINE",
    difficulty: "EPIC",
    cadence: "WEEKLY",
    category: "Strategy",
  },

  // VITALITY (10 templates)
  {
    slug: "vit-hydrate-goal",
    title: "Personalized Daily Hydration",
    description: "Drink adequate water throughout the day according to your body's personal needs.",
    attribute: "VITALITY",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Nutrition",
  },
  {
    slug: "vit-meditate-10",
    title: "10-Minute Mindfulness Meditation",
    description: "Practice mindful breathing or body-scan meditation using calm, quiet presence.",
    attribute: "VITALITY",
    difficulty: "EASY",
    cadence: "DAILY",
    category: "Mindfulness",
  },
  {
    slug: "vit-prepare-whole-meal",
    title: "Cook a Fresh, Nourishing Meal",
    description: "Prepare a meal from wholesome, unprocessed ingredients with veggies and lean protein.",
    attribute: "VITALITY",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Nutrition",
  },
  {
    slug: "vit-gratitude-journal",
    title: "Write 3 Gratitude Reflections",
    description: "Write down 3 specific things you are genuinely grateful for today.",
    attribute: "VITALITY",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Reflection",
  },
  {
    slug: "vit-time-in-nature",
    title: "Spend 20 Minutes Outdoors in Nature",
    description: "Walk in a park, garden, or tree-lined area absorbing natural sunlight without headphones.",
    attribute: "VITALITY",
    difficulty: "EASY",
    cadence: "DAILY",
    category: "Recovery",
  },
  {
    slug: "vit-screen-free-winddown",
    title: "Screen-Free Evening Winddown",
    description: "Power down phones, computers, and televisions at least 45 minutes before sleep.",
    attribute: "VITALITY",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Sleep",
  },
  {
    slug: "vit-health-checkup",
    title: "Schedule Routine Health Appointment",
    description: "Book an appointment for a dental checkup, annual physical, or vision exam.",
    attribute: "VITALITY",
    difficulty: "MEDIUM",
    cadence: "ONCE",
    category: "Health",
  },
  {
    slug: "vit-restorative-nap",
    title: "20-Minute Restorative Power Nap",
    description: "Lie down in a dark, quiet room for a 20-minute restorative rest without falling into deep sleep.",
    attribute: "VITALITY",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Rest",
  },
  {
    slug: "vit-foam-roll",
    title: "Foam Rolling & Myofascial Release",
    description: "Roll out sore muscles, calves, glutes, and upper back for 15 minutes.",
    attribute: "VITALITY",
    difficulty: "EASY",
    cadence: "WEEKLY",
    category: "Recovery",
  },
  {
    slug: "vit-sunlight-exposure",
    title: "Morning Sunlight Exposure within 1 Hour",
    description: "Get 10 minutes of natural outdoor sunlight into your eyes to anchor your circadian rhythm.",
    attribute: "VITALITY",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Circadian",
  },

  // CHARISMA (10 templates)
  {
    slug: "cha-call-loved-one",
    title: "Call a Friend or Family Member",
    description: "Reach out and have a meaningful 15-minute voice conversation to strengthen a bond.",
    attribute: "CHARISMA",
    difficulty: "EASY",
    cadence: "WEEKLY",
    category: "Connection",
  },
  {
    slug: "cha-give-compliment",
    title: "Share a Sincere, Specific Compliment",
    description: "Acknowledge a colleague or friend's hard work or thoughtful quality with sincere words.",
    attribute: "CHARISMA",
    difficulty: "TRIVIAL",
    cadence: "DAILY",
    category: "Kindness",
  },
  {
    slug: "cha-practice-presentation",
    title: "Rehearse a Presentation Out Loud",
    description: "Stand up and deliver your talk or speech slides aloud with confident vocal projection.",
    attribute: "CHARISMA",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Speaking",
  },
  {
    slug: "cha-update-portfolio",
    title: "Refine Professional Profile or Portfolio",
    description: "Polish case studies, resume bullet points, or your personal website bio.",
    attribute: "CHARISMA",
    difficulty: "MEDIUM",
    cadence: "WEEKLY",
    category: "Career",
  },
  {
    slug: "cha-apply-opportunity",
    title: "Submit an Application for an Opportunity",
    description: "Apply for a grant, conference speaker spot, job, or freelance collaboration.",
    attribute: "CHARISMA",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Career",
  },
  {
    slug: "cha-thoughtful-message",
    title: "Send a Thoughtful Professional Message",
    description: "Check in with a mentor or collaborator with an update or useful article they would enjoy.",
    attribute: "CHARISMA",
    difficulty: "EASY",
    cadence: "WEEKLY",
    category: "Networking",
  },
  {
    slug: "cha-attend-meetup",
    title: "Attend a Community Meetup or Event",
    description: "Participate in a local tech, creative, or hobby group and converse with new people.",
    attribute: "CHARISMA",
    difficulty: "EPIC",
    cadence: "WEEKLY",
    category: "Community",
  },
  {
    slug: "cha-mock-interview",
    title: "Practice Mock Interview Questions",
    description: "Answer behavioral or technical interview questions using the STAR framework.",
    attribute: "CHARISMA",
    difficulty: "HARD",
    cadence: "WEEKLY",
    category: "Interview",
  },
  {
    slug: "cha-active-listening",
    title: "Practice Pure Active Listening Today",
    description: "In conversations today, focus 100% on understanding rather than waiting to speak.",
    attribute: "CHARISMA",
    difficulty: "MEDIUM",
    cadence: "DAILY",
    category: "Communication",
  },
  {
    slug: "cha-help-stranger",
    title: "Perform an Unprompted Act of Service",
    description: "Help a neighbor, volunteer, or assist someone without expecting anything in return.",
    attribute: "CHARISMA",
    difficulty: "EASY",
    cadence: "WEEKLY",
    category: "Service",
  },
];
